#include<iostream.h>
#include<conio.h>
void main()
{
 clrscr();
 int a=5;
 int m[5][5];
 cout<<"lets begin:\n";
 for(int i=0;i<a;i++)
 {
 for(int j=0;j<a;j++)
 {
  cin>>m[i][j];
  }
  cout<<"\n";
  }
  cout<<":) ALL DONE !!\n";
  for(i=0;i<a;i++)
  {
   for(int j=0;j<a;j++)
   {
    cout<<m[i][j]<<"\t";
   }
   cout<<"\n";
   }
   //___________-------------------------
  cout<<"comment:Addition";
  for(int i=0;i<a;i++

  getch();
  }