.PHONY: clean All

All:
	@echo "----------Building project:[ Training - Debug ]----------"
	@cd "Training" && "$(MAKE)" -f  "Training.mk"
clean:
	@echo "----------Cleaning project:[ Training - Debug ]----------"
	@cd "Training" && "$(MAKE)" -f  "Training.mk" clean
